### ISSUE TITLE
Cancel concurrent CI runs

### ISSUE THREAD

**Issue by gussmith23** [uwsampl/lakeroad#298]
https://www.meziantou.net/how-to-cancel-github-workflows-when-pushing-new-commits-on-a-branch.htm

**Comment by kscharan** [comment]
Hello @gussmith23, 
I would like to work on this issue. 
One query before I get started, what is your expectation for concurrent runs?
You want to only cancel in-progress runs for branches other than main?

**Comment by gussmith23** [comment]
Thanks for being interested!!
>You want to only cancel in-progress runs for branches other than main?
That seems like a good place to start!

**Comment by kscharan** [comment]
Hello @gussmith23 
Issue addressed here: [https://github.com/uwsampl/lakeroad/pull/300](url)
Please have a look.
